export interface companyType {}

export const company = [
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '1',
        name: 'autobusmagico 1',
        filial_company: null,
        abbreviation: 'autm',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Pública',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: ['Ferroviarios', 'Ferries'],
        bank_details: [{
            bank: '618035b1e554bf6c947be3dc', 
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas 1',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '2',
        name: 'autobusmagico 2',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'G-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Pepito Perez',
        id_number: 'V-123456789',
        company_type: 'Privada',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0108',
            bank_name: 'Banco Provincial, S.A.',
            bank_agency: 'cc plaza las americas 2',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '3',
        filial_company: '1',
        name: 'autobusmagico 3',
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Pepito Gonzalez',
        id_number: 'V-123456789',
        company_type: 'Privada',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0134',
            bank_name: 'Banesco S.A.C.A.',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '4',
        name: 'autobusmagico 4',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Mixta',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '5',  
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '6',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        
        id: '6181542ae554bf6c947be41c',
        company_code: '7',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '8',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '9',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank:'618035b1e554bf6c947be3dc',
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '10',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: [],
        bank_details: [{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
    {
        id: '6181542ae554bf6c947be41c',
        company_code: '11',
        name: 'autobusmagico',
        filial_company: null,
        abbreviation: 'autmg',
        nif: 'J-123456789123',
        address: 'Av. Washington, Artigas (Av. San Martín)',
        city: 'Caracas',
        state: 'Distrito Capital',
        legal_representative: 'Carmen Perez',
        id_number: 'V-123456789',
        company_type: 'Publica',
        logo: 'blob',
        active: true,
        department: 1,
        transportation_means: ['moto'],
        bank_details:[{
            bank_code: '0102',
            bank_name: 'Banco de Venezuela S.A.I.C.A',
            bank_agency: 'cc plaza las americas',
            account_type: 'corriente',
            account_number: '01021234567891234567',
            swift_code: 'VZLAVECA',
        }],
        created_by: 'autobusmagico',
        created_on: 'new Date()',
    },
]
